#!/bin/bash

# run script $1 for all arguments in file $2, for seeds between optional $3 and $4 (default 1),
# on right cluster (cpu or gpu)

# mkdir -p slurm_log
# mkdir -p log
# mkdir -p ckpt

echo "saving old argument file to history"
cat $2 >> .$2.hist
cat $2 > .$2.bak

# python -c "from lib.cmd_utils import create_dataset_before; create_dataset_before('$2')"

rm -f $2.gpu
rm -f $2.cpu
python -c "from lib.cmd_utils import assign_cluster; assign_cluster('$2')"

echo "generating seeded args"
python -c "from lib.cmd_utils import seedify; seedify('$2.gpu')" $3 $4
python -c "from lib.cmd_utils import seedify; seedify('$2.cpu')" $3 $4

# clear
cat $2.gpu
echo
read -p "Are you sure you want to run these arguments on gpu? (y/Y to proceed) " -n 1 -r
echo
if [[ $REPLY =~ ^[yY]$ ]]
then
        sbatch --array=1-$(grep "" -c $2.gpu.seeded) slurm_script_gpu.sbatch $1 $2
fi

# clear
cat $2.cpu
echo
read -p "Are you sure you want to run these arguments on cpu? (y/Y to proceed) " -n 1 -r
echo
if [[ $REPLY =~ ^[yY]$ ]]
then
        sbatch --array=1-$(grep "" -c $2.cpu.seeded) slurm_script_cpu.sbatch $1 $2
fi
