#!/bin/sh
python compare_to_tcl.py -seed 1 -dseed 0 -lr 1e-3 -maxsteps 1e5 -mlayers 1 -nlayers 1 -hdim 10 -kmeans
python compare_to_tcl.py -seed 2 -dseed 0 -lr 1e-4 -maxsteps 1e5 -mlayers 1 -nlayers 1 -hdim 20 -kmeans
python compare_to_tcl.py -seed 3 -dseed 0 -lr 1e-3 -maxsteps 1e5 -mlayers 1 -nlayers 1 -hdim 10 -kmeans
python compare_to_tcl.py -seed 4 -dseed 0 -lr 1e-4 -maxsteps 1e5 -mlayers 1 -nlayers 1 -hdim 20 -kmeans
python compare_to_tcl.py -seed 5 -dseed 0 -lr 1e-4 -maxsteps 1e5 -mlayers 1 -nlayers 1 -hdim 10 -kmeans
python compare_to_tcl.py -seed 1 -dseed 1 -lr 1e-3 -maxsteps 1e5 -mlayers 1 -nlayers 1 -hdim 10 -kmeans
python compare_to_tcl.py -seed 2 -dseed 1 -lr 1e-4 -maxsteps 1e5 -mlayers 1 -nlayers 1 -hdim 20 -kmeans
python compare_to_tcl.py -seed 3 -dseed 1 -lr 1e-3 -maxsteps 1e5 -mlayers 1 -nlayers 1 -hdim 10 -kmeans
python compare_to_tcl.py -seed 4 -dseed 1 -lr 1e-4 -maxsteps 1e5 -mlayers 1 -nlayers 1 -hdim 20 -kmeans
python compare_to_tcl.py -seed 5 -dseed 1 -lr 1e-4 -maxsteps 1e5 -mlayers 1 -nlayers 1 -hdim 10 -kmeans
python compare_to_tcl.py -seed 1 -dseed 2 -lr 1e-3 -maxsteps 1e5 -mlayers 1 -nlayers 1 -hdim 10 -kmeans
python compare_to_tcl.py -seed 2 -dseed 2 -lr 1e-4 -maxsteps 1e5 -mlayers 1 -nlayers 1 -hdim 20 -kmeans
python compare_to_tcl.py -seed 3 -dseed 2 -lr 1e-3 -maxsteps 1e5 -mlayers 1 -nlayers 1 -hdim 10 -kmeans
python compare_to_tcl.py -seed 4 -dseed 2 -lr 1e-4 -maxsteps 1e5 -mlayers 1 -nlayers 1 -hdim 20 -kmeans
python compare_to_tcl.py -seed 5 -dseed 2 -lr 1e-4 -maxsteps 1e5 -mlayers 1 -nlayers 1 -hdim 10 -kmeans
python compare_to_tcl.py -seed 1 -dseed 3 -lr 1e-3 -maxsteps 1e5 -mlayers 1 -nlayers 1 -hdim 10 -kmeans
python compare_to_tcl.py -seed 2 -dseed 3 -lr 1e-4 -maxsteps 1e5 -mlayers 1 -nlayers 1 -hdim 20 -kmeans
python compare_to_tcl.py -seed 3 -dseed 3 -lr 1e-3 -maxsteps 1e5 -mlayers 1 -nlayers 1 -hdim 10 -kmeans
python compare_to_tcl.py -seed 4 -dseed 3 -lr 1e-4 -maxsteps 1e5 -mlayers 1 -nlayers 1 -hdim 20 -kmeans
python compare_to_tcl.py -seed 5 -dseed 3 -lr 1e-4 -maxsteps 1e5 -mlayers 1 -nlayers 1 -hdim 10 -kmeans
python compare_to_tcl.py -seed 1 -dseed 4 -lr 1e-3 -maxsteps 1e5 -mlayers 1 -nlayers 1 -hdim 10 -kmeans
python compare_to_tcl.py -seed 2 -dseed 4 -lr 1e-4 -maxsteps 1e5 -mlayers 1 -nlayers 1 -hdim 20 -kmeans
python compare_to_tcl.py -seed 3 -dseed 4 -lr 1e-3 -maxsteps 1e5 -mlayers 1 -nlayers 1 -hdim 10 -kmeans
python compare_to_tcl.py -seed 4 -dseed 4 -lr 1e-4 -maxsteps 1e5 -mlayers 1 -nlayers 1 -hdim 20 -kmeans
python compare_to_tcl.py -seed 5 -dseed 4 -lr 1e-4 -maxsteps 1e5 -mlayers 1 -nlayers 1 -hdim 10 -kmeans
python compare_to_tcl.py -seed 1 -dseed 5 -lr 1e-3 -maxsteps 1e5 -mlayers 1 -nlayers 1 -hdim 10 -kmeans
python compare_to_tcl.py -seed 2 -dseed 5 -lr 1e-4 -maxsteps 1e5 -mlayers 1 -nlayers 1 -hdim 20 -kmeans
python compare_to_tcl.py -seed 3 -dseed 5 -lr 1e-3 -maxsteps 1e5 -mlayers 1 -nlayers 1 -hdim 10 -kmeans
python compare_to_tcl.py -seed 4 -dseed 5 -lr 1e-4 -maxsteps 1e5 -mlayers 1 -nlayers 1 -hdim 20 -kmeans
python compare_to_tcl.py -seed 5 -dseed 5 -lr 1e-4 -maxsteps 1e5 -mlayers 1 -nlayers 1 -hdim 10 -kmeans
python compare_to_tcl.py -seed 1 -dseed 6 -lr 1e-3 -maxsteps 1e5 -mlayers 1 -nlayers 1 -hdim 10 -kmeans
python compare_to_tcl.py -seed 2 -dseed 6 -lr 1e-4 -maxsteps 1e5 -mlayers 1 -nlayers 1 -hdim 20 -kmeans
python compare_to_tcl.py -seed 3 -dseed 6 -lr 1e-3 -maxsteps 1e5 -mlayers 1 -nlayers 1 -hdim 10 -kmeans
python compare_to_tcl.py -seed 4 -dseed 6 -lr 1e-4 -maxsteps 1e5 -mlayers 1 -nlayers 1 -hdim 20 -kmeans
python compare_to_tcl.py -seed 5 -dseed 6 -lr 1e-4 -maxsteps 1e5 -mlayers 1 -nlayers 1 -hdim 10 -kmeans
python compare_to_tcl.py -seed 1 -dseed 7 -lr 1e-3 -maxsteps 1e5 -mlayers 1 -nlayers 1 -hdim 10 -kmeans
python compare_to_tcl.py -seed 2 -dseed 7 -lr 1e-4 -maxsteps 1e5 -mlayers 1 -nlayers 1 -hdim 20 -kmeans
python compare_to_tcl.py -seed 3 -dseed 7 -lr 1e-3 -maxsteps 1e5 -mlayers 1 -nlayers 1 -hdim 10 -kmeans
python compare_to_tcl.py -seed 4 -dseed 7 -lr 1e-4 -maxsteps 1e5 -mlayers 1 -nlayers 1 -hdim 20 -kmeans
python compare_to_tcl.py -seed 5 -dseed 7 -lr 1e-4 -maxsteps 1e5 -mlayers 1 -nlayers 1 -hdim 10 -kmeans
python compare_to_tcl.py -seed 1 -dseed 8 -lr 1e-3 -maxsteps 1e5 -mlayers 1 -nlayers 1 -hdim 10 -kmeans
python compare_to_tcl.py -seed 2 -dseed 8 -lr 1e-4 -maxsteps 1e5 -mlayers 1 -nlayers 1 -hdim 20 -kmeans
python compare_to_tcl.py -seed 3 -dseed 8 -lr 1e-3 -maxsteps 1e5 -mlayers 1 -nlayers 1 -hdim 10 -kmeans
python compare_to_tcl.py -seed 4 -dseed 8 -lr 1e-4 -maxsteps 1e5 -mlayers 1 -nlayers 1 -hdim 20 -kmeans
python compare_to_tcl.py -seed 5 -dseed 8 -lr 1e-4 -maxsteps 1e5 -mlayers 1 -nlayers 1 -hdim 10 -kmeans
python compare_to_tcl.py -seed 1 -dseed 9 -lr 1e-3 -maxsteps 1e5 -mlayers 1 -nlayers 1 -hdim 10 -kmeans
python compare_to_tcl.py -seed 2 -dseed 9 -lr 1e-4 -maxsteps 1e5 -mlayers 1 -nlayers 1 -hdim 20 -kmeans
python compare_to_tcl.py -seed 3 -dseed 9 -lr 1e-3 -maxsteps 1e5 -mlayers 1 -nlayers 1 -hdim 10 -kmeans
python compare_to_tcl.py -seed 4 -dseed 9 -lr 1e-4 -maxsteps 1e5 -mlayers 1 -nlayers 1 -hdim 20 -kmeans
python compare_to_tcl.py -seed 5 -dseed 9 -lr 1e-4 -maxsteps 1e5 -mlayers 1 -nlayers 1 -hdim 10 -kmeans
python compare_to_tcl.py -seed 1 -dseed 0 -lr 1e-3 -maxsteps 1e5 -mlayers 2 -nlayers 2 -hdim 10 -kmeans
python compare_to_tcl.py -seed 2 -dseed 0 -lr 1e-4 -maxsteps 1e5 -mlayers 2 -nlayers 2 -hdim 20 -kmeans
python compare_to_tcl.py -seed 3 -dseed 0 -lr 1e-3 -maxsteps 1e5 -mlayers 2 -nlayers 2 -hdim 10 -kmeans
python compare_to_tcl.py -seed 4 -dseed 0 -lr 1e-4 -maxsteps 1e5 -mlayers 2 -nlayers 2 -hdim 20 -kmeans
python compare_to_tcl.py -seed 5 -dseed 0 -lr 1e-4 -maxsteps 1e5 -mlayers 2 -nlayers 2 -hdim 10 -kmeans
python compare_to_tcl.py -seed 1 -dseed 1 -lr 1e-3 -maxsteps 1e5 -mlayers 2 -nlayers 2 -hdim 10 -kmeans
python compare_to_tcl.py -seed 2 -dseed 1 -lr 1e-4 -maxsteps 1e5 -mlayers 2 -nlayers 2 -hdim 20 -kmeans
python compare_to_tcl.py -seed 3 -dseed 1 -lr 1e-3 -maxsteps 1e5 -mlayers 2 -nlayers 2 -hdim 10 -kmeans
python compare_to_tcl.py -seed 4 -dseed 1 -lr 1e-4 -maxsteps 1e5 -mlayers 2 -nlayers 2 -hdim 20 -kmeans
python compare_to_tcl.py -seed 5 -dseed 1 -lr 1e-4 -maxsteps 1e5 -mlayers 2 -nlayers 2 -hdim 10 -kmeans
python compare_to_tcl.py -seed 1 -dseed 2 -lr 1e-3 -maxsteps 1e5 -mlayers 2 -nlayers 2 -hdim 10 -kmeans
python compare_to_tcl.py -seed 2 -dseed 2 -lr 1e-4 -maxsteps 1e5 -mlayers 2 -nlayers 2 -hdim 20 -kmeans
python compare_to_tcl.py -seed 3 -dseed 2 -lr 1e-3 -maxsteps 1e5 -mlayers 2 -nlayers 2 -hdim 10 -kmeans
python compare_to_tcl.py -seed 4 -dseed 2 -lr 1e-4 -maxsteps 1e5 -mlayers 2 -nlayers 2 -hdim 20 -kmeans
python compare_to_tcl.py -seed 5 -dseed 2 -lr 1e-4 -maxsteps 1e5 -mlayers 2 -nlayers 2 -hdim 10 -kmeans
python compare_to_tcl.py -seed 1 -dseed 3 -lr 1e-3 -maxsteps 1e5 -mlayers 2 -nlayers 2 -hdim 10 -kmeans
python compare_to_tcl.py -seed 2 -dseed 3 -lr 1e-4 -maxsteps 1e5 -mlayers 2 -nlayers 2 -hdim 20 -kmeans
python compare_to_tcl.py -seed 3 -dseed 3 -lr 1e-3 -maxsteps 1e5 -mlayers 2 -nlayers 2 -hdim 10 -kmeans
python compare_to_tcl.py -seed 4 -dseed 3 -lr 1e-4 -maxsteps 1e5 -mlayers 2 -nlayers 2 -hdim 20 -kmeans
python compare_to_tcl.py -seed 5 -dseed 3 -lr 1e-4 -maxsteps 1e5 -mlayers 2 -nlayers 2 -hdim 10 -kmeans
python compare_to_tcl.py -seed 1 -dseed 4 -lr 1e-3 -maxsteps 1e5 -mlayers 2 -nlayers 2 -hdim 10 -kmeans
python compare_to_tcl.py -seed 2 -dseed 4 -lr 1e-4 -maxsteps 1e5 -mlayers 2 -nlayers 2 -hdim 20 -kmeans
python compare_to_tcl.py -seed 3 -dseed 4 -lr 1e-3 -maxsteps 1e5 -mlayers 2 -nlayers 2 -hdim 10 -kmeans
python compare_to_tcl.py -seed 4 -dseed 4 -lr 1e-4 -maxsteps 1e5 -mlayers 2 -nlayers 2 -hdim 20 -kmeans
python compare_to_tcl.py -seed 5 -dseed 4 -lr 1e-4 -maxsteps 1e5 -mlayers 2 -nlayers 2 -hdim 10 -kmeans
python compare_to_tcl.py -seed 1 -dseed 5 -lr 1e-3 -maxsteps 1e5 -mlayers 2 -nlayers 2 -hdim 10 -kmeans
python compare_to_tcl.py -seed 2 -dseed 5 -lr 1e-4 -maxsteps 1e5 -mlayers 2 -nlayers 2 -hdim 20 -kmeans
python compare_to_tcl.py -seed 3 -dseed 5 -lr 1e-3 -maxsteps 1e5 -mlayers 2 -nlayers 2 -hdim 10 -kmeans
python compare_to_tcl.py -seed 4 -dseed 5 -lr 1e-4 -maxsteps 1e5 -mlayers 2 -nlayers 2 -hdim 20 -kmeans
python compare_to_tcl.py -seed 5 -dseed 5 -lr 1e-4 -maxsteps 1e5 -mlayers 2 -nlayers 2 -hdim 10 -kmeans
python compare_to_tcl.py -seed 1 -dseed 6 -lr 1e-3 -maxsteps 1e5 -mlayers 2 -nlayers 2 -hdim 10 -kmeans
python compare_to_tcl.py -seed 2 -dseed 6 -lr 1e-4 -maxsteps 1e5 -mlayers 2 -nlayers 2 -hdim 20 -kmeans
python compare_to_tcl.py -seed 3 -dseed 6 -lr 1e-3 -maxsteps 1e5 -mlayers 2 -nlayers 2 -hdim 10 -kmeans
python compare_to_tcl.py -seed 4 -dseed 6 -lr 1e-4 -maxsteps 1e5 -mlayers 2 -nlayers 2 -hdim 20 -kmeans
python compare_to_tcl.py -seed 5 -dseed 6 -lr 1e-4 -maxsteps 1e5 -mlayers 2 -nlayers 2 -hdim 10 -kmeans
python compare_to_tcl.py -seed 1 -dseed 7 -lr 1e-3 -maxsteps 1e5 -mlayers 2 -nlayers 2 -hdim 10 -kmeans
python compare_to_tcl.py -seed 2 -dseed 7 -lr 1e-4 -maxsteps 1e5 -mlayers 2 -nlayers 2 -hdim 20 -kmeans
python compare_to_tcl.py -seed 3 -dseed 7 -lr 1e-3 -maxsteps 1e5 -mlayers 2 -nlayers 2 -hdim 10 -kmeans
python compare_to_tcl.py -seed 4 -dseed 7 -lr 1e-4 -maxsteps 1e5 -mlayers 2 -nlayers 2 -hdim 20 -kmeans
python compare_to_tcl.py -seed 5 -dseed 7 -lr 1e-4 -maxsteps 1e5 -mlayers 2 -nlayers 2 -hdim 10 -kmeans
python compare_to_tcl.py -seed 1 -dseed 8 -lr 1e-3 -maxsteps 1e5 -mlayers 2 -nlayers 2 -hdim 10 -kmeans
python compare_to_tcl.py -seed 2 -dseed 8 -lr 1e-4 -maxsteps 1e5 -mlayers 2 -nlayers 2 -hdim 20 -kmeans
python compare_to_tcl.py -seed 3 -dseed 8 -lr 1e-3 -maxsteps 1e5 -mlayers 2 -nlayers 2 -hdim 10 -kmeans
python compare_to_tcl.py -seed 4 -dseed 8 -lr 1e-4 -maxsteps 1e5 -mlayers 2 -nlayers 2 -hdim 20 -kmeans
python compare_to_tcl.py -seed 5 -dseed 8 -lr 1e-4 -maxsteps 1e5 -mlayers 2 -nlayers 2 -hdim 10 -kmeans
python compare_to_tcl.py -seed 1 -dseed 9 -lr 1e-3 -maxsteps 1e5 -mlayers 2 -nlayers 2 -hdim 10 -kmeans
python compare_to_tcl.py -seed 2 -dseed 9 -lr 1e-4 -maxsteps 1e5 -mlayers 2 -nlayers 2 -hdim 20 -kmeans
python compare_to_tcl.py -seed 3 -dseed 9 -lr 1e-3 -maxsteps 1e5 -mlayers 2 -nlayers 2 -hdim 10 -kmeans
python compare_to_tcl.py -seed 4 -dseed 9 -lr 1e-4 -maxsteps 1e5 -mlayers 2 -nlayers 2 -hdim 20 -kmeans
python compare_to_tcl.py -seed 5 -dseed 9 -lr 1e-4 -maxsteps 1e5 -mlayers 2 -nlayers 2 -hdim 10 -kmeans
python compare_to_tcl.py -seed 1 -dseed 0 -lr 1e-3 -maxsteps 1e5 -mlayers 4 -nlayers 4 -hdim 10 -kmeans
python compare_to_tcl.py -seed 2 -dseed 0 -lr 1e-4 -maxsteps 1e5 -mlayers 4 -nlayers 4 -hdim 20 -kmeans
python compare_to_tcl.py -seed 3 -dseed 0 -lr 1e-3 -maxsteps 1e5 -mlayers 4 -nlayers 4 -hdim 10 -kmeans
python compare_to_tcl.py -seed 4 -dseed 0 -lr 1e-4 -maxsteps 1e5 -mlayers 4 -nlayers 4 -hdim 20 -kmeans
python compare_to_tcl.py -seed 5 -dseed 0 -lr 1e-4 -maxsteps 1e5 -mlayers 4 -nlayers 4 -hdim 10 -kmeans
python compare_to_tcl.py -seed 1 -dseed 1 -lr 1e-3 -maxsteps 1e5 -mlayers 4 -nlayers 4 -hdim 10 -kmeans
python compare_to_tcl.py -seed 2 -dseed 1 -lr 1e-4 -maxsteps 1e5 -mlayers 4 -nlayers 4 -hdim 20 -kmeans
python compare_to_tcl.py -seed 3 -dseed 1 -lr 1e-3 -maxsteps 1e5 -mlayers 4 -nlayers 4 -hdim 10 -kmeans
python compare_to_tcl.py -seed 4 -dseed 1 -lr 1e-4 -maxsteps 1e5 -mlayers 4 -nlayers 4 -hdim 20 -kmeans
python compare_to_tcl.py -seed 5 -dseed 1 -lr 1e-4 -maxsteps 1e5 -mlayers 4 -nlayers 4 -hdim 10 -kmeans
python compare_to_tcl.py -seed 1 -dseed 2 -lr 1e-3 -maxsteps 1e5 -mlayers 4 -nlayers 4 -hdim 10 -kmeans
python compare_to_tcl.py -seed 2 -dseed 2 -lr 1e-4 -maxsteps 1e5 -mlayers 4 -nlayers 4 -hdim 20 -kmeans
python compare_to_tcl.py -seed 3 -dseed 2 -lr 1e-3 -maxsteps 1e5 -mlayers 4 -nlayers 4 -hdim 10 -kmeans
python compare_to_tcl.py -seed 4 -dseed 2 -lr 1e-4 -maxsteps 1e5 -mlayers 4 -nlayers 4 -hdim 20 -kmeans
python compare_to_tcl.py -seed 5 -dseed 2 -lr 1e-4 -maxsteps 1e5 -mlayers 4 -nlayers 4 -hdim 10 -kmeans
python compare_to_tcl.py -seed 1 -dseed 3 -lr 1e-3 -maxsteps 1e5 -mlayers 4 -nlayers 4 -hdim 10 -kmeans
python compare_to_tcl.py -seed 2 -dseed 3 -lr 1e-4 -maxsteps 1e5 -mlayers 4 -nlayers 4 -hdim 20 -kmeans
python compare_to_tcl.py -seed 3 -dseed 3 -lr 1e-3 -maxsteps 1e5 -mlayers 4 -nlayers 4 -hdim 10 -kmeans
python compare_to_tcl.py -seed 4 -dseed 3 -lr 1e-4 -maxsteps 1e5 -mlayers 4 -nlayers 4 -hdim 20 -kmeans
python compare_to_tcl.py -seed 5 -dseed 3 -lr 1e-4 -maxsteps 1e5 -mlayers 4 -nlayers 4 -hdim 10 -kmeans
python compare_to_tcl.py -seed 1 -dseed 4 -lr 1e-3 -maxsteps 1e5 -mlayers 4 -nlayers 4 -hdim 10 -kmeans
python compare_to_tcl.py -seed 2 -dseed 4 -lr 1e-4 -maxsteps 1e5 -mlayers 4 -nlayers 4 -hdim 20 -kmeans
python compare_to_tcl.py -seed 3 -dseed 4 -lr 1e-3 -maxsteps 1e5 -mlayers 4 -nlayers 4 -hdim 10 -kmeans
python compare_to_tcl.py -seed 4 -dseed 4 -lr 1e-4 -maxsteps 1e5 -mlayers 4 -nlayers 4 -hdim 20 -kmeans
python compare_to_tcl.py -seed 5 -dseed 4 -lr 1e-4 -maxsteps 1e5 -mlayers 4 -nlayers 4 -hdim 10 -kmeans
python compare_to_tcl.py -seed 1 -dseed 5 -lr 1e-3 -maxsteps 1e5 -mlayers 4 -nlayers 4 -hdim 10 -kmeans
python compare_to_tcl.py -seed 2 -dseed 5 -lr 1e-4 -maxsteps 1e5 -mlayers 4 -nlayers 4 -hdim 20 -kmeans
python compare_to_tcl.py -seed 3 -dseed 5 -lr 1e-3 -maxsteps 1e5 -mlayers 4 -nlayers 4 -hdim 10 -kmeans
python compare_to_tcl.py -seed 4 -dseed 5 -lr 1e-4 -maxsteps 1e5 -mlayers 4 -nlayers 4 -hdim 20 -kmeans
python compare_to_tcl.py -seed 5 -dseed 5 -lr 1e-4 -maxsteps 1e5 -mlayers 4 -nlayers 4 -hdim 10 -kmeans
python compare_to_tcl.py -seed 1 -dseed 6 -lr 1e-3 -maxsteps 1e5 -mlayers 4 -nlayers 4 -hdim 10 -kmeans
python compare_to_tcl.py -seed 2 -dseed 6 -lr 1e-4 -maxsteps 1e5 -mlayers 4 -nlayers 4 -hdim 20 -kmeans
python compare_to_tcl.py -seed 3 -dseed 6 -lr 1e-3 -maxsteps 1e5 -mlayers 4 -nlayers 4 -hdim 10 -kmeans
python compare_to_tcl.py -seed 4 -dseed 6 -lr 1e-4 -maxsteps 1e5 -mlayers 4 -nlayers 4 -hdim 20 -kmeans
python compare_to_tcl.py -seed 5 -dseed 6 -lr 1e-4 -maxsteps 1e5 -mlayers 4 -nlayers 4 -hdim 10 -kmeans
python compare_to_tcl.py -seed 1 -dseed 7 -lr 1e-3 -maxsteps 1e5 -mlayers 4 -nlayers 4 -hdim 10 -kmeans
python compare_to_tcl.py -seed 2 -dseed 7 -lr 1e-4 -maxsteps 1e5 -mlayers 4 -nlayers 4 -hdim 20 -kmeans
python compare_to_tcl.py -seed 3 -dseed 7 -lr 1e-3 -maxsteps 1e5 -mlayers 4 -nlayers 4 -hdim 10 -kmeans
python compare_to_tcl.py -seed 4 -dseed 7 -lr 1e-4 -maxsteps 1e5 -mlayers 4 -nlayers 4 -hdim 20 -kmeans
python compare_to_tcl.py -seed 5 -dseed 7 -lr 1e-4 -maxsteps 1e5 -mlayers 4 -nlayers 4 -hdim 10 -kmeans
python compare_to_tcl.py -seed 1 -dseed 8 -lr 1e-3 -maxsteps 1e5 -mlayers 4 -nlayers 4 -hdim 10 -kmeans
python compare_to_tcl.py -seed 2 -dseed 8 -lr 1e-4 -maxsteps 1e5 -mlayers 4 -nlayers 4 -hdim 20 -kmeans
python compare_to_tcl.py -seed 3 -dseed 8 -lr 1e-3 -maxsteps 1e5 -mlayers 4 -nlayers 4 -hdim 10 -kmeans
python compare_to_tcl.py -seed 4 -dseed 8 -lr 1e-4 -maxsteps 1e5 -mlayers 4 -nlayers 4 -hdim 20 -kmeans
python compare_to_tcl.py -seed 5 -dseed 8 -lr 1e-4 -maxsteps 1e5 -mlayers 4 -nlayers 4 -hdim 10 -kmeans
python compare_to_tcl.py -seed 1 -dseed 9 -lr 1e-3 -maxsteps 1e5 -mlayers 4 -nlayers 4 -hdim 10 -kmeans
python compare_to_tcl.py -seed 2 -dseed 9 -lr 1e-4 -maxsteps 1e5 -mlayers 4 -nlayers 4 -hdim 20 -kmeans
python compare_to_tcl.py -seed 3 -dseed 9 -lr 1e-3 -maxsteps 1e5 -mlayers 4 -nlayers 4 -hdim 10 -kmeans
python compare_to_tcl.py -seed 4 -dseed 9 -lr 1e-4 -maxsteps 1e5 -mlayers 4 -nlayers 4 -hdim 20 -kmeans
python compare_to_tcl.py -seed 5 -dseed 9 -lr 1e-4 -maxsteps 1e5 -mlayers 4 -nlayers 4 -hdim 10 -kmeans
