# dataset
nps: 1000
ns: 40
dl: 5
dd: 5
nl: 3
s: 1
p: 'gauss'
act: 'xtanh'
uncentered: false
noisy: false
staircase: false

# model args
n_layers: 3
hidden_dim: 100
activation: 'xtanh'
ica: false
initialize: true
batch_norm: false
tcl: false

# learning
a: 500
b: 5
c: 5
d: 5
gamma: 0
lr: 0.01
batch_size: 64
epochs: 20
no_scheduler: false
scheduler_tol: 3
anneal: false
anneal_epoch: 20
