# dataset
nps: 1000
ns: 40
dl: 5
dd: 5
nl: 3
s: 1
p: 'gauss'
act: 'xtanh'
uncentered: false
noisy: false

# model args
n_layers: 3
hidden_dim: 100
activation: 'xtanh'
ica: true

# learning
a: 100
b: 1
c: 0
d: 8
gamma: 0
lr: 0.0001
batch_size: 64
epochs: 20
no_scheduler: false
anneal: false
