data:
  data_dim: 5
  latent_dim: 5
  n_segments: 40
  n_layers: 3
  n_obs_per_seg: 1000
  data_seed: 1
  centered: true
  noisy: 0
  staircase: false
  activation: 'xtanh'


training:
  batch_size: 32
  n_epochs: 50
  lr: 0.001
  scheduler: true
  scheduler_tol: 3
  a: 30
  b: 1
  c: 1
  d: 5
  anneal: true
  anneal_epoch: 20

model:
  base: 'ivae'
  batch_norm: false
  initialize: true
  n_hidden: 6
  hidden_dim: 100
  activation: 'lrelu'
