data:
  data_dim: 5
  latent_dim: 5
  n_segments: 40
  n_layers: 3
  n_obs_per_seg: 1000
  data_seed: 1
  centered: true
  noisy: false
  staircase: false


training:
  batch_size: 64
  n_epochs: 20
  lr: 0.01
  scheduler_tol: 3
  scheduler: true
  a: 1000
  b: 1
  c: 1
  d: 1
  anneal: true
  anneal_epoch: 12

model:
  base: 'vae'
  batch_norm: false
  initialize: true
  n_hidden: 3
  hidden_dim: 100
  activation: 'lrelu'
